### ISSUE TITLE
When using beforeSave on object with a Pointer column - "error: ParseError code=111 error=schema mismatch for Test.test1; expected Pointer<Test1> but got Object"

### ISSUE THREAD

**Issue by jaysonng** [netreconlab/parse-server-swift#65]
When using beforeSave trigger on an object that has a pointer to another object like so:

```swift
struct Test: ParseObject {

    //: These are required for `ParseObject`.
    var originalData: Data?
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    var name: String?
    var test1: Test1?
}

struct Test1: ParseObject {

    //: These are required for `ParseObject`.
    var originalData: Data?
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    var description: String?
    var test2: Test2?
    var test3: Test3?
}
```

Doing nothing but just having the beforeSave trigger on produces a schema mismatch error where it expects a Pointer to the sub-object.

```swift
func beforeSaveTest(req: Request) async throws -> HookResponse<Test> {

        if let error: HookResponse<Test> = checkHeaders(req) { return error }
        
        var parseRequest = try req.content.decode(HookTrigObjReq<User, Test>.self)
        let options      = try parseRequest.options(req)
        
        if parseRequest.user != nil {
            parseRequest = try await parseRequest.hydrateUser(options: options, request: req)
        }
        
        guard let object = parseRequest.object else {
            return ParseHookResponse(error: .init(code: .missingObjectId,
                                                  message: "Object not sent in request."))
        }
        
        return HookResponse(success: object)
        
    }
```

I encountered this as I was trying to save a complex object with multiple pointers and tested with these Test objects getting the same result. 

```error
error: ParseError code=111 error=schema mismatch for Test.test1; expected Pointer<Test1> but got Object
```

**Comment by cbaker6** [comment]
See my response here: https://github.com/netreconlab/Parse-Swift/issues/151#issuecomment-1936048482

**Comment by jaysonng** [comment]
> See my response here: [netreconlab/Parse-Swift#151 (comment)](https://github.com/netreconlab/Parse-Swift/issues/151#issuecomment-1936048482)

I think this is a different problem. it wasn't a matter of it having he same scheme. 

I was just passing an already existing object, which has pointed to another object (already existing) 

it didn't have to create anything. But passing the object through Parse-Server-Swift BeforeSave causes this error.

**Comment by jaysonng** [comment]
![Screenshot 2024-02-17 at 11 36 49 PM](https://github.com/netreconlab/parse-server-swift/assets/440445/3fdd3887-bd08-4610-a934-4df39fb136a8)

As an example. I just tried to update "wohoo" to "wohoo1"

and again got this error:

```
error: ParseError code=111 error=schema mismatch for Test.test1; expected Pointer<Test1> but got Object
```

Even when I try it on Dashboard.

![Screenshot 2024-02-17 at 11 39 58 PM](https://github.com/netreconlab/parse-server-swift/assets/440445/50df082b-62e3-41cb-8d7e-6e66b03124fb)

**Comment by cbaker6** [comment]
I don’t see a “beforeSave” trigger in the code you provided. I do see “beforeSaveTest” but that’s not a beforeSave trigger

**Comment by jaysonng** [comment]
> I don’t see a “beforeSave” trigger in the code you provided. I do see “beforeSaveTest” but that’s not a beforeSave trigger

sorry, I call beforeSaveTest using the boot routes builder like so.

```swift
    func boot(routes: RoutesBuilder) throws {
        
        let lokalityGroup = routes.grouped("lokality")
        //: Triggers
        lokalityGroup.post("save", "before", object: Lokality.self,
                           trigger: .beforeSave, use: beforeSave)
        lokalityGroup.post("save", "before", object: Test.self,
                           trigger: .beforeSave, use: beforeSaveTest)
   }
```

**Comment by cbaker6** [comment]
It still looks like the same problem as https://github.com/netreconlab/parse-server-swift/issues/65#issuecomment-1950226051 to me. ParseServerSwift uses ParseSwift, the beforeSave webhook is called before an object is created on the server so it will run into the same issue. I think you can improve on your systems design to circumvent this, like not saving empty items for no reason. You should save objects when they actually have data. I gave some examples in the previous links. If you insist on keeping your design, you may need to remove your “beforeSave” code using ParseServerSwift, and us the JS Cloud Code for that part.

You could also never create empty objects on the client, use ParseServerSwift beforeSave to create them if they are nil

**Comment by jaysonng** [comment]
It's not empty though. 

They're already there and existing.

**Comment by jaysonng** [comment]
> ![Screenshot 2024-02-17 at 11 36 49 PM](https://github.com/netreconlab/parse-server-swift/assets/440445/3fdd3887-bd08-4610-a934-4df39fb136a8)
> 
> 
> 
> As an example. I just tried to update "wohoo" to "wohoo1"
> 
> 
> 
> and again got this error:
> 
> 
> 
> ```
> 
> error: ParseError code=111 error=schema mismatch for Test.test1; expected Pointer<Test1> but got Object
> 
> ```
> 
> 
> 
> Even when I try it on Dashboard.
> 
> 
> 
> ![Screenshot 2024-02-17 at 11 39 58 PM](https://github.com/netreconlab/parse-server-swift/assets/440445/50df082b-62e3-41cb-8d7e-6e66b03124fb)
> 
> 

See this. The info is already there on the dashboard. 

And i still get the error.

**Comment by jaysonng** [comment]
So it's not a matter of creating empty objects this time around but how ParseServerSwift handles saving a Pointer but receiving an object in beforeSave. 

Somehow it sees the struct and thinks it's a 'Pointer<Test1>' but really it's getting a 'Test1' - in beforeSave.

**Comment by jaysonng** [comment]
I'll give it a try on more of my other classes that have the same setup of pointers a do a beforeSave that already has existing data and see if i get it saving. 

The Test classes I use are for posting here on Github but I initially encountered the error on my other classes.

**Comment by jaysonng** [comment]
I got it to save just now by changing `var test1: Test1?` on my Test struct by changing it to a Pointer<Test1>? and it saved as expected on ParseDashboard. I just updated an existing object.

```swift
struct Test: ParseObject {

    //: These are required for `ParseObject`.
    var originalData: Data?
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    var name: String?
    var test1: Test1?
}
```
to 
```swift
var test1: Pointer<Test1>?
```

**Comment by cbaker6** [comment]
I recommend looking at the unit tests and try to create a PR which replicates your scenario. You should be able to do it in the ParseSwift repo as it supports all of the hooks. The test case will most likely go into this file: https://github.com/netreconlab/Parse-Swift/blob/main/Tests/ParseSwiftTests/ParseHookTriggerTests.swift.

**Comment by jaysonng** [comment]
> I recommend looking at the unit tests and try to create a PR which replicates your scenario. You should be able to do it in the ParseSwift repo as it supports all of the hooks. The test case will most likely go into this file: https://github.com/netreconlab/Parse-Swift/blob/main/Tests/ParseSwiftTests/ParseHookTriggerTests.swift.

I'll look into unit testing. My coding skills haven't gotten that far yet. 😄 

thanks

**Comment by jaysonng** [comment]
> What happens when you try the following?
> 
> `test1.set(\.name, “woohoo1”)` and then save? When updating individual properties on an object that’s already created, it’s better to use set anyways: https://github.com/netreconlab/Parse-Swift/blob/b3169f2b438df9bb1d14935246be0a462c97c42f/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L241-L261

```swift
func testTest() async {
        do {

            let testQuery = Test.query()
            var result = try await testQuery.first(options: [.usePrimaryKey])
//            result.name = "wohoo1234"
            result.set(\.name, to: "wohoo4321")
            try await result.save(options: [.usePrimaryKey])

            print("Successfully updated: \(result.objectId.logable)")

        } catch {
            print("error: \(error.localizedDescription)")
            XCTAssertNil("Update Test failed")
        }

    }
```

still the same error
`error: ParseError code=111 error=schema mismatch for Test.test1; expected Pointer<Test1> but got Object`

**Comment by cbaker6** [comment]
> I'm still trying to figure out how to do a Unit Test without an actual database though - for the PR.

The test file I referenced before shows how to do this:

Server response: https://github.com/netreconlab/Parse-Swift/blob/b3169f2b438df9bb1d14935246be0a462c97c42f/Tests/ParseSwiftTests/ParseHookTriggerTests.swift#L188-L201

Expected JSON: https://github.com/netreconlab/Parse-Swift/blob/b3169f2b438df9bb1d14935246be0a462c97c42f/Tests/ParseSwiftTests/ParseHookTriggerTests.swift#L72-L82

There are 1000+ examples in the current unit tests. Look for one that seems more intuitive, then go to more complex

**Comment by jaysonng** [comment]
How do I actually trigger the beforeSave Trigger in a test? I can't seem to find an existing test that actually calls it or runs it. everything seems to be just creating / updating hooks.

**Comment by jaysonng** [comment]
@cbaker6 

I haven't been able to successfully do a unit test with my case but I have figured out what's causing the problem.

In JS CloudCode, the object I get out of the Request vs the paramsRequest.object (which was decoded) is structured differently.

In JS CloudCode, the object keeps the `__type: Pointer` on the object. In ParseServerSwift, the line

`parseRequest = req.content.decode(...)` 

converts the Pointer to just an Object which is then what we pass to the ParseHookResponse at the end of the beforeSave

`return ParseHookResponse(success: object)`

Question is, how do I pull out the data I need  from the Request (while in the beforeSave trigger function) without decoding it or decode it in a way that I keep the Pointer structure?

```swift
func beforeSaveTest(req: Request) async throws -> ParseHookResponse<Test> {
        
        if let error: HookResponse<Test> = checkHeaders(req) { return error }
        
// object structure is changed here which JS validation errors out later in SchemaController.js
        var parseRequest = try req.content.decode(ParseHookTriggerObjectRequest<User, Test>.self)
        let options      = try parseRequest.options(req)
        
        if parseRequest.user != nil {
            parseRequest = try await parseRequest.hydrateUser(options: options, request: req)
        }
        
        guard var object = parseRequest.object else {
            return ParseHookResponse(error: .init(code: .missingObjectId,
                                                  message: "Object not sent in request."))
        }

        return HookResponse(success: object)
    }
```

[SchemaController.js](https://github.com/parse-community/parse-server/blob/ac7399b226d0d1eb62142727ce98e543689b4d89/src/Controllers/SchemaController.js#L1037) in parse-server

**Comment by cbaker6** [comment]
I think I may understand where the issue is at now, at this line: https://github.com/netreconlab/parse-server-swift/blob/12db8741080808642435fb1a99ef64557e809b53/Sources/ParseServerSwift/Parse.swift#L49-L50

Change to:

```swift
// Parse uses tailored encoders/decoders. These can be retrieved from any ParseObject
ContentConfiguration.global.use(encoder: User.getEncoder(), for: .json)
```

Delete all of your hooks and functions before connecting the updated ParseServer and let me know if this works. It's possible this may introduce other issues that weren't originally there since parse-server-swift is only connecting to a ParseServer and not something that expects traditional JSON. If there are new issues, we will need to look further into how to better utilize Vapors encoder configuration.

**Comment by jaysonng** [comment]
Error:

![Screenshot 2024-02-23 at 1 33 02 PM](https://github.com/netreconlab/parse-server-swift/assets/440445/c4ecd617-15ed-4dfc-b6e7-a880e0dd18f6)

needed to add `as! ContentCoder` because of this error:

![Screenshot 2024-02-23 at 1 33 53 PM](https://github.com/netreconlab/parse-server-swift/assets/440445/3850ea85-3d5f-4ea2-bb0f-a896f60cd288)

**Comment by jaysonng** [comment]
Commenting out line 50, allows me to build and run Parse-Server-Swift but I get the same schema error on calling beforeSave.

![Screenshot 2024-02-23 at 5 13 44 PM](https://github.com/netreconlab/parse-server-swift/assets/440445/88c4970b-7803-496a-b95b-a24f275d3fe2)

**Comment by jaysonng** [comment]
I've been trying to pull the data out "as is" of the HTTP header Request but couldn't figure it out. 

I'm not well versed in decoding yet. usually I just decode json.

**Comment by cbaker6** [comment]
It doesn't look like it's a decoding issue, it looks more like an encoding issue because the parse-server expects Parse json to look a particular way. In particular objects that can be pointers should be sent as pointers. I'll look into a fix when I get some time next week.

**Comment by cbaker6** [comment]
@jaysonng can you test out #71 and let me know if it addresses the issue?

**Comment by jaysonng** [comment]
hi @cbaker6 ! sorry I haven't checked github in a while. I'll update to the latest versions and test this out. thanks!

**Comment by jaysonng** [comment]
I just updated to 0.12 and haven't totally tested it out with triggers. but, I do get this error:

![Screenshot 2024-08-02 at 11 13 44 PM](https://github.com/user-attachments/assets/84cd23c5-d09d-4c1a-9a1a-2637e55b7f07)

which isn't there on a clean install of 0.12. everything runs smoothly. 

But once I place my files in, the error comes up. 

I'm not sure if it has something to do with my User object being extended and having more custom properties? I had to delete the User.swift file that comes with 0.12 and use my own. 

I test this error by switching branches in my private repo. Because it's private, I couldn't just pull from a public fork of 0.12 so i downloaded the files and just placed it in my existing project. 

Do you have a quick insight on why I'm getting this error ?

**Comment by cbaker6** [comment]
You are not adding the files correctly to your repo, specifically the extension of ParseEncoder that conforms to ContentEncoder, https://github.com/netreconlab/parse-server-swift/pull/71/files. You shouldn’t have this problem if you are using the repo as a package in your project as the versions package up all of the files.

You can usually tell if you’ve copied something wrong by testing main repo, if the issue isn’t there, it’s most likely your own code

**Comment by jaysonng** [comment]
> You are not adding the files correctly to your repo, specifically the extension of ParseEncoder that conforms to ContentEncoder, https://github.com/netreconlab/parse-server-swift/pull/71/files. You shouldn’t have this problem if you are using the repo as a package in your project as the versions package up all of the files.
> 
> You can usually tell if you’ve copied something wrong by testing main repo, if the issue isn’t there, it’s most likely your own code

ok ill try it again. thanks!

**Comment by jaysonng** [comment]
thanks I see it. I overwrote the Parse+Vapor.swift file accidentally.

**Comment by cbaker6** [comment]
I recommend you start using the package. I changed a number of files in recent updates and there’s no telling what files I’ll change in the future. IMO, your current way of maintaining your private repo isn’t sustainable and you will run into similar issues in the future. Your current way also makes it hard for me to diagnose issues as I don’t know what version you really have in your repo since you are copy/pasting code

**Comment by jaysonng** [comment]
agreed. I'll setup everything again having parse-server-swift as a package this time around instead of editing a fork which I had before. 

a couple of questions though, 
1. how does that work with routes.swift since I have some custom code in there, can I extend func routes(_) ?

```swift
// swiftlint:disable:next cyclomatic_complexity function_body_length
func routes(_ app: Application) throws {
        
    let env = try Environment.detect()
    let port = Environment.get("PARSE_SERVER_SWIFT_PORT")
    print("ENVIRONMENT: \(env.name)")
    print("PORT: \(port.logable)")

    app.routes.defaultMaxBodySize = "1500kb"

    do {
        try app.register(collection: ImageCollection())
        try app.register(collection: UserCollection())
        try app.register(collection: TagCollection())
    } catch {
        print(error)
    }
    
//    ... truncated
```

2. since I already have a struct User.swift setup which I've added custom properties, i need to delete the default User.swift struct included in Parse-Swift-Server. Does this mean i need to rename and reorganize how I use my User object? 

thanks,

**Comment by jaysonng** [comment]
Hi @cbaker6 , I need some help with the setup using ParseServerSwift.

for some reason, my custom routes.swift in my project folder isn't being  used and the default routes.swift file is being used when I start and run my app.

![Screenshot 2024-08-04 at 7 27 59 PM](https://github.com/user-attachments/assets/5db49131-4386-4419-a321-923f764b5161)

What setting should I be looking at? Something with the targets?

```swift

// swift-tools-version:5.10
import PackageDescription

let package = Package(
    name: "BusogCloud",
    platforms: [
        .iOS(.v13),
        .macCatalyst(.v13),
        .macOS(.v10_15),
        .tvOS(.v13),
        .watchOS(.v6)
    ],
    products: [
            .library(name: "BusogCloud", targets: ["BusogCloud"])
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.99.3"),
        // 🔵 Non-blocking, event-driven networking for Swift. Used for custom executors
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.65.0"),
        .package(url: "https://github.com/netreconlab/Parse-Swift.git", from: "5.11.2"),
        .package(url: "https://github.com/netreconlab/ParseServerSwift", .upToNextMajor(from: "0.12.0")),
        .package(url: "https://github.com/lokalnewsapp/Countries", .upToNextMajor(from: "1.0.0"))
    ],
    targets: [
        .target(name: "BusogCloud",
        dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "ParseSwift", package: "Parse-Swift"),
                .product(name: "ParseServerSwift", package: "ParseServerSwift"),
                .product(name: "Countries", package: "Countries")
            ]
        ),
        .executableTarget(
            name: "App",
            dependencies: [.target(name: "BusogCloud")],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides/blob/main/docs/building.md#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .testTarget(
            name: "AppTests",
            dependencies: [
                .target(name: "App"),
                .product(name: "XCTVapor", package: "vapor"),
            ],
            swiftSettings: swiftSettings
        )
    ]
)

var swiftSettings: [SwiftSetting] { [
    .enableUpcomingFeature("DisableOutwardActorInference"),
    .enableExperimentalFeature("StrictConcurrency"),
] }
```

This is my Package.swift file if it helps.

Thanks!

**Comment by jaysonng** [comment]
I know its not working because when i run the app, the default hooks and triggers that i dont have in my routes.swift gets loaded up into webhooks and none of my custom hooks get loaded.

**Comment by cbaker6** [comment]
You would need to show what configuration function you are using, but if the's the one provided by ParseServerSwift, you would need to create your own and use your own routes until I provide the ability to pass routes: https://github.com/netreconlab/parse-server-swift/blob/336b0d2302954ce1f36087e26c37dc8304a29d60/Sources/ParseServerSwift/configure.swift#L18-L19

**Comment by jaysonng** [comment]
![Screenshot 2024-08-05 at 6 58 52 PM](https://github.com/user-attachments/assets/e6331aaa-8bd2-45ed-b984-bfeb174526d3)
entrypoint.swift 

error: cannot find my custom routes function which is in my BusogCloud folder routes.swift file.

![Screenshot 2024-08-05 at 6 59 18 PM](https://github.com/user-attachments/assets/a4286da7-6f95-4799-ae54-3cd9b57dba1c)

and I also added my own configure.swift file as you suggested:
![Screenshot 2024-08-05 at 6 59 30 PM](https://github.com/user-attachments/assets/9b13ca98-c271-4820-a7f7-29c8d6754013)

but I'm currently still stuck at entrypoint in App executabletarget not seeing BusogCloud target files.

**Comment by jaysonng** [comment]
finally got past this problem by just using the default App folder provided by Vapor's default project as the executableTarget and not modifying Package.swift to use .target() like suggested in the current ReadMe file. 

My current Package.swift file just reads 

```swift 

let package = Package(
    name: "BusogCloud",
    platforms: [
        .iOS(.v13),
        .macCatalyst(.v13),
        .macOS(.v10_15),
        .tvOS(.v13),
        .watchOS(.v6)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.99.3"),
        // 🔵 Non-blocking, event-driven networking for Swift. Used for custom executors
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.65.0"),
        .package(url: "https://github.com/netreconlab/Parse-Swift.git", from: "5.11.2"),
        .package(url: "https://github.com/netreconlab/ParseServerSwift", .upToNextMajor(from: "0.12.0")),
        .package(url: "https://github.com/lokalnewsapp/Countries", .upToNextMajor(from: "1.0.0"))
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "ParseSwift", package: "Parse-Swift"),
                .product(name: "ParseServerSwift", package: "ParseServerSwift"),
                .product(name: "Countries", package: "Countries")
                ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides/blob/main/docs/building.md#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .testTarget(
            name: "AppTests",
            dependencies: [
                .target(name: "App"),
                .product(name: "XCTVapor", package: "vapor"),
            ],
            swiftSettings: swiftSettings
        )
    ]
)
```

I'm not sure if this is a bug on the relationship between Vapor, packages and ParseServerSwift (as a dependency) where I can't use targets.

I'm off to test the triggers now. thanks.

**Comment by cbaker6** [comment]
You probably just need to make your routes function `public`, https://github.com/netreconlab/parse-server-swift/blob/7c11bd334017ec38c5578c7a4b5a3f7c3df385ff/Sources/ParseServerSwift/routes.swift#L5

> and I also added my own configure.swift file as you suggested:

This was only needed if you are using version <0.13, if you are using >=0.13, you can pass any Routes method to `` as I showed in #74

**Comment by jaysonng** [comment]
regarding dockerfile, should I be copying the one in ParseServerSwift package for my project or the default one by Vapor?

**Comment by jaysonng** [comment]
> You probably just need to make your routes function `public`,

I just tried this and it worked. I also needed to add import BusogCloud (my app). 

thanks! :) the busogRoutes function is being seen now. 

I got a new problem now I need to debug. The whole thing crashes when I run my project.

![Screenshot 2024-08-06 at 9 22 30 AM](https://github.com/user-attachments/assets/c0628c4a-fd27-47da-ac6b-b3fe0f9f714a)

**Comment by cbaker6** [comment]
> regarding dockerfile, should I be copying the one in ParseServerSwift package for my project or the default one by Vapor?

The docker file in `ParseServerSwift` was generated from an older version of vapor. It was then updated to work with Parse. It’s possible, this file may not be using the latest docker settings Vapor suggets. In this case, since you generated your current vapor project with the latest version of vapor (I’m assumming) then you can compare and submit PR’s with the changes to this repo in the future.

**Comment by jaysonng** [comment]
> @jaysonng can you test out #71 by upgrading to https://github.com/netreconlab/parse-server-swift/releases/tag/0.11.1 and let me know if it addresses the issue?

Hi @cbaker6, unfortunately I'm still getting the same error:
![Screenshot 2024-08-07 at 12 58 34 AM](https://github.com/user-attachments/assets/425e5c10-a0ff-4ecc-86a0-a89853a257db)
![Screenshot 2024-08-07 at 12 50 00 AM](https://github.com/user-attachments/assets/830c7006-42d2-4af1-845a-b763a96739bb)

these screenshots are from the ParseDashboard error when just editing an existing data. Changing a property to `Pointer<XXXX>` does fix it but then I have to change every reference to it by doing `.toPointer()`

**Comment by jaysonng** [comment]
This is for running beforeSave trigger by the way.

**Comment by jaysonng** [comment]
1. Uncaught exception Error when trying to update a field in a Test object with this beforeSave code which returns ParseHookResponse<Bool>.  ( this one is new to me, I didn't notice this before )
```swift
    func beforeSaveTest(req: Request) async throws -> ParseHookResponse<Bool> {
        
        if let error: ParseHookResponse<Bool> = checkHeaders(req) {
            return error
        }
        
        let parseRequest = try req.content
            .decode(ParseHookTriggerObjectRequest<User, Test>.self)

        req.logger.info("A LiveQuery event occured: \(parseRequest)")
        return ParseHookResponse(success: true)

    }
```
I get an error but does not crash my ParseServerSwift project.
```
info: beforeSave triggered for Test for user undefined:
  Input: {"name":"jayson21","createdAt":"2024-02-18T00:27:35.235Z","updatedAt":"2024-08-06T16:57:26.391Z","test1":{"__type":"Pointer","className":"Test1","objectId":"rRW7jehY8s"},"objectId":"yMzqHQwyhB"}
  Result: {"object":true} {"className":"Test","triggerType":"beforeSave"}
error: Uncaught internal server error. Cannot create property 'updatedAt' on boolean 'true' {"stack":"TypeError: Cannot create property 'updatedAt' on boolean 'true'\n    at /Users/jayson/Projects/Busog/parse-server/node_modules/parse-server/lib/RestWrite.js:316:29\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
TypeError: Cannot create property 'updatedAt' on boolean 'true'
    at /Users/jayson/Projects/Busog/parse-server/node_modules/parse-server/lib/RestWrite.js:316:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at ServerResponse.header (/Users/jayson/Projects/Busog/parse-server/node_modules/express/lib/response.js:795:10)
    at ServerResponse.send (/Users/jayson/Projects/Busog/parse-server/node_modules/express/lib/response.js:175:12)
    at errorHandler (/Users/jayson/Projects/Busog/parse-server/files/errorHandler.js:6:21)
    at Layer.handle_error (/Users/jayson/Projects/Busog/parse-server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/jayson/Projects/Busog/parse-server/node_modules/express/lib/router/index.js:326:13)
    at /Users/jayson/Projects/Busog/parse-server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/jayson/Projects/Busog/parse-server/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/jayson/Projects/Busog/parse-server/node_modules/express/lib/router/index.js:280:10)
```



2. When I change ParseHookResponse<Bool> to ParseHookResponse<Test> There is NO ERROR. it updates the object properly.
note here that I'm passing a new Test object to ParseHookResponse.

```swift
 func beforeSaveTest(req: Request) async throws -> ParseHookResponse<Test> {
        
        if let error: ParseHookResponse<Test> = checkHeaders(req) {
            return error
        }
        
        let parseRequest = try req.content
            .decode(ParseHookTriggerObjectRequest<User, Test>.self)

        req.logger.info("A LiveQuery event occured: \(parseRequest)")
        
        return ParseHookResponse(success: Test())

    }
```


3. The main error is when we pass and return the object param taken from parseRequest like so:

```swift
 func beforeSaveTest(req: Request) async throws -> HookResponse<Test> {

        if let error: ParseHookResponse<Test> = checkHeaders(req) {
            return error
        }

        var parseRequest = try req.content
            .decode(ParseHookTriggerObjectRequest<User, Test>.self)
    
        let options      = try parseRequest.options(req)
        
        if parseRequest.user != nil {
            parseRequest = try await parseRequest.hydrateUser(options: options, request: req)
        }
        
        guard let object = parseRequest.object else {
            return ParseHookResponse(error: .init(code: .missingObjectId,
                                                  message: "Object not sent in request."))
        }
        
        req.logger.info("A LiveQuery event occured: \(parseRequest)")
        return ParseHookResponse(success: object)

    }
```

The full error:

```
info: beforeSave triggered for Test for user undefined:
  Input: {"name":"jayson12s2","createdAt":"2024-02-18T00:27:35.235Z","updatedAt":"2024-08-07T02:31:56.122Z","test1":{"__type":"Pointer","className":"Test1","objectId":"rRW7jehY8s"},"objectId":"yMzqHQwyhB"}
  Result: {"object":{"name":"jayson12s2","objectId":"yMzqHQwyhB","test1":{"objectId":"rRW7jehY8s"}}} {"className":"Test","triggerType":"beforeSave"}
error: schema mismatch for Test.test1; expected Pointer<Test1> but got Object {"code":111,"stack":"Error: schema mismatch for Test.test1; expected Pointer<Test1> but got Object\n    at SchemaController.enforceFieldExists (/Users/jayson/Projects/Busog/parse-server/node_modules/parse-server/lib/Controllers/SchemaController.js:1121:15)\n    at SchemaController.validateObject (/Users/jayson/Projects/Busog/parse-server/node_modules/parse-server/lib/Controllers/SchemaController.js:1252:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
```

and of course I can't just .toPointer() object to pass to ParseHookResponse.

**Comment by jaysonng** [comment]
is the structure of a parseRequest.object different from a newly created ParseObject  ( ie Test() ?
